### ISSUE TITLE
Cannot read properties of undefined (reading 'addIceCandidate')

### ISSUE THREAD

**Issue by schniggie** [fkasler/cuddlephish#1]
Just see an empty white page, in the JavaScript Console I get:

```
ndex):84 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at Socket.<anonymous> ((index):84:6)
    at Emitter.emit (index.mjs:136:20)
    at Socket.emitEvent (socket.js:498:20)
    at Socket.onevent (socket.js:485:18)
    at Socket.onpacket (socket.js:455:22)
    at Emitter.emit (index.mjs:136:20)
    at manager.js:204:18
(
```

Within the /admin interface I can see the session, small thumbnail is also correct. Any idea?

**Comment by fkasler** [comment]
This error indicates that there was a problem setting up the WebRTC video feed from the automated browser running on your server and the browser you are viewing from. You have not said what browser you are testing with, so I can't even attempt to replicate the issue, but here are a couple ideas based on just the info provided:

1) You might be trying to test this locally. In which case, re-read the setup instructions.
2) You might be viewing the site as a victim before the server has a chance to spawn an automated browser. Did you try just refreshing the page after a bit?
3) Your server may not have enough resources to run the attack. I've tested on VMs with 4 Gig of RAM, and it works, but definitely works way better with at least 8. Keep in mind, at a minimum, the server needs to run a browser and screen buffer per user.
4) The broadcast and cuddlephish html pages both use a single Google hosted STUN server 'stun:stun.l.google.com:19302' to broker WebRTC connections. If you are having an issue with reaching that service, you can mod the code to point to another STUN server, or even an array of STUN servers. On some networks, you may have to use a TURN server instead. I have left a commented out example config for TURN in the project for those that need/prefer it.

Let me know if any of this helps. And, if you have more issues, please help me out by providing more information that might help me replicate the problem.

**Comment by fkasler** [comment]
@schniggie have you had a chance to try out any of the suggestions? I would like to close this issue if possible.

**Comment by fkasler** [comment]
No response... Closing this issue.

**Comment by clod81** [comment]
I'm experiencing the same issue. I used this for tests a few weeks ago and worked with no issues.
I read the troubleshooting readme section, but I can reach the stun fine using that test page, and in the logs I see:

```
client_ip: 203.xxx.xxx.xxx
Socket connected! wywHo8l3qdnZTJZUAAAr
candidate: 5zvokZnvQYI3A1mEAAAp to wywHo8l3qdnZTJZUAAAr
video_stream_offer
viewer_id: wywHo8l3qdnZTJZUAAAr
offer: [object Object]
video_stream_answer
broadcaster_id: 5zvokZnvQYI3A1mEAAAp
answer: [object Object]
candidate: wywHo8l3qdnZTJZUAAAr to 5zvokZnvQYI3A1mEAAAp
candidate: wywHo8l3qdnZTJZUAAAr to 5zvokZnvQYI3A1mEAAAp
Socket connected! z8pjV4D4UIaFyGZlAAAt
```

As the victim I see a blank page, in the admin area I see the correct target page.

Happy to provide more info. I'm also trying to understand what's happening, but so far been unable to. [@fkasler]

**Comment by clod81** [comment]
So, I tried a second time using an EC2 in AWS rather than a local VPS I would need for this job.
It works all fine.
Any idea what would stop this tool from working on a particular VPS @fkasler ? It seems to have unrestricted outbound traffic, so unsure what the issue might be. On VPS that doesn't work, it's Debian 11, and all installed following readme
