### ISSUE TITLE
Not functioning on other ports rather than 80, 443

### ISSUE THREAD

**Issue by thistehneisen** [fkasler/cuddlephish#4]
If the host has 80/443 ports taken, the application doesn't function properly, e.g.:
`sudo docker run -p 1339:80 -p 1440:443 -p 2019:2019 -v $PWD/Caddyfile:/etc/caddy/Caddyfile caddy:latest`

**Comment by fkasler** [comment]
You will need to instruct Caddy to bind those alternate ports in your Caddyfile:

https://stackoverflow.com/questions/51209710/specify-caddy-listening-port

Per this stackoverflow you can either add the port to the domain like ```mydomain.com:1440``` OR use a block at the beginning of your Caddyfile like:
```
 {
    http_port 1339
    https_port 1440
}
```
Then you would skip the port translation in the docker run command:
```sudo docker run -p 1339:1339 -p 1440:1440 -p 2019:2019 -v $PWD/Caddyfile:/etc/caddy/Caddyfile caddy:latest```
